---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: credentials-updater
  namespace: poolc-system
  labels:
    app.kubernetes.io/name: credentials-updater
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poolc:credentials-updater
  labels:
    app.kubernetes.io/name: credentials-updater
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poolc:credentials-updater:read-secret
  namespace: poolc-system
  labels:
    app.kubernetes.io/name: credentials-updater
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poolc:credentials-updater
  labels:
    app.kubernetes.io/name: credentials-updater
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: credentials-updater
    namespace: poolc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poolc:credentials-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poolc:credentials-updater:read-secret
  namespace: poolc-system
  labels:
    app.kubernetes.io/name: credentials-updater
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: credentials-updater
    namespace: poolc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: poolc:credentials-updater:read-secret
